name: Git_Workshop_Demo

on:
  push:
    branches:
        - 'feature/**'
        - 'bugfix/**'
        - 'chore/**'
        - 'hotfix/**'
env:
    SERVER_IP: 'xxx-x-x-x'
    COMPANY_NAME: 'IOIP'
    REPO_NAME: ${{github.repository}}


jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
        PHONE: '0987654321'
    steps: 
        - run: echo "${{github.actor}} ${{env.PHONE}} ${{vars.APP_NAME}} ${{secrets.API_KEY}}"
        - run: echo "Hello ${{env.COMPANY_NAME}}"
        - run: echo ${{env.REPO_NAME}}
        - run: echo ${{env.PHONE}}
        - run: echo ${{secrets.SRV_IP}}
        
  job-2:
    runs-on: ubuntu-latest
    steps: 
        - run: echo "Hello  ${{env.COMPANY_NAME}}"
        - run: echo ${{env.SERVER_IP}}
        - run: echo ${{vars.APP_DEV_BY}}
